"""BYOC snapshot storage and MapViewer response enrichment."""

from copy import deepcopy
import logging

from plone import api
from zope.annotation.interfaces import IAnnotations


BYOC_SNAPSHOT_KEY = "clms.types.mapviewer_byoc_snapshot"
logger = logging.getLogger(__name__)


def normalize_collection_id(value):
    """Return a collection UUID without the optional ``byoc-`` prefix."""
    value = str(value or "").strip().lower()
    if value.startswith("byoc-"):
        value = value[5:]
    return value


def get_byoc_snapshot():
    """Return the last validated BYOC snapshot stored on the portal."""
    portal = api.portal.get()
    return IAnnotations(portal).get(BYOC_SNAPSHOT_KEY, {})


def set_byoc_snapshot(snapshot):
    """Atomically replace the generated BYOC snapshot."""
    portal = api.portal.get()
    IAnnotations(portal)[BYOC_SNAPSHOT_KEY] = deepcopy(snapshot)


def _browser_collection(download_information, snapshot):
    """Find the Browser collection used by a CMS dataset."""
    if not isinstance(download_information, dict):
        return None
    snapshot = snapshot if snapshot is not None else get_byoc_snapshot()
    collections = (
        snapshot.get("collections", {})
        if isinstance(snapshot, dict)
        else {}
    )
    for item in download_information.get("items", []):
        if not isinstance(item, dict):
            continue
        collection_id = normalize_collection_id(item.get("byoc_collection"))
        configuration = collections.get(collection_id)
        if configuration is not None:
            return configuration
    return None


def _layer_key(value):
    """Normalize a layer identifier or title for exact comparison."""
    return str(value or "").strip().casefold()


def _match_layers(layers, browser_layers):
    """Match Browser layer metadata without guessing ambiguous pairs."""
    matches = {}
    available = set(range(len(browser_layers)))

    for layer_index, layer in enumerate(layers):
        layer_id = _layer_key(layer.get("LayerId"))
        title = _layer_key(layer.get("Title"))
        id_candidates = []
        title_candidates = []
        for browser_index in available:
            browser_layer = browser_layers[browser_index]
            browser_id = _layer_key(browser_layer.get("layerId"))
            browser_title = _layer_key(browser_layer.get("title"))
            if layer_id and layer_id == browser_id:
                id_candidates.append(browser_index)
            if title and title == browser_title:
                title_candidates.append(browser_index)
        candidates = id_candidates or title_candidates
        if len(candidates) == 1:
            matches[layer_index] = candidates[0]
            available.remove(candidates[0])

    unmatched = [index for index in range(len(layers)) if index not in matches]
    if len(unmatched) == 1 and len(available) == 1:
        matches[unmatched[0]] = available.pop()
    return matches


def enrich_mapviewer_dataset(
    serialized_dataset,
    download_information,
    snapshot=None,
):
    """Add Browser collection and layer data to a response copy."""
    enriched = deepcopy(serialized_dataset)
    if not isinstance(enriched, dict):
        return enriched

    configuration = _browser_collection(download_information, snapshot)
    if configuration is None:
        return enriched

    enriched["browserCollectionId"] = configuration.get(
        "browserCollectionId"
    )
    layers = enriched.get("Layer", [])
    browser_layers = configuration.get("layers", [])
    if not isinstance(layers, list) or not isinstance(browser_layers, list):
        return enriched

    matches = _match_layers(
        layers,
        browser_layers,
    )
    if not matches:
        logger.warning(
            "MapViewer BYOC collection matched but no layer matched: "
            "dataset=%s collection=%s cms_layers=%s browser_layers=%s",
            enriched.get("DatasetId"),
            configuration.get("browserCollectionId"),
            [layer.get("LayerId") for layer in layers],
            [layer.get("layerId") for layer in browser_layers],
        )

    for layer_index, browser_index in matches.items():
        browser_layer = browser_layers[browser_index]
        layer = layers[layer_index]
        has_low_resolution = bool(browser_layer.get("hasLowRes"))
        layer["description"] = browser_layer.get("description")
        layer["hasLowRes"] = has_low_resolution
        layer["resolution_data"] = {}
        if has_low_resolution:
            layer["resolution_data"] = {
                key: deepcopy(browser_layer.get(key))
                for key in (
                    "highRes",
                    "lowRes",
                    "thresholdMetersPerPixel",
                    "thresholdScale",
                )
            }
    logger.debug(
        "MapViewer BYOC dataset enriched: "
        "dataset=%s collection=%s layers=%s",
        enriched.get("DatasetId"),
        configuration.get("browserCollectionId"),
        len(matches),
    )
    return enriched
